development:
  adapter: postgresql
  encoding: unicode
  database: chicago_development
  pool: 5
  username: larkfofty
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: chicago_test
  pool: 5
  username: larkfofty
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: chicago_production
  pool: 5
  username: larkfofty
  password: